//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace administrator.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("administrator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1627009688_12_p_rozovii_fon_oboi_na_rabochii_stol_12 {
            get {
                object obj = ResourceManager.GetObject("1627009688_12-p-rozovii-fon-oboi-na-rabochii-stol-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1627014998_8_p_fon_dlya_yutuba_rozovii_8 {
            get {
                object obj = ResourceManager.GetObject("1627014998_8-p-fon-dlya-yutuba-rozovii-8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1627014998_8_p_fon_dlya_yutuba_rozovii_81 {
            get {
                object obj = ResourceManager.GetObject("1627014998_8-p-fon-dlya-yutuba-rozovii-81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1627014998_8_p_fon_dlya_yutuba_rozovii_82 {
            get {
                object obj = ResourceManager.GetObject("1627014998_8-p-fon-dlya-yutuba-rozovii-82", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1627014998_8_p_fon_dlya_yutuba_rozovii_83 {
            get {
                object obj = ResourceManager.GetObject("1627014998_8-p-fon-dlya-yutuba-rozovii-83", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1627014998_8_p_fon_dlya_yutuba_rozovii_84 {
            get {
                object obj = ResourceManager.GetObject("1627014998_8-p-fon-dlya-yutuba-rozovii-84", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1627014998_8_p_fon_dlya_yutuba_rozovii_85 {
            get {
                object obj = ResourceManager.GetObject("1627014998_8-p-fon-dlya-yutuba-rozovii-85", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1639789403_1_catherineasquithgallery_com_p_rozovii_fon_nezhnii_gorizontalnii_1 {
            get {
                object obj = ResourceManager.GetObject("1639789403_1-catherineasquithgallery-com-p-rozovii-fon-nezhnii-gorizontalnii-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1653390585_56_celes_club_p_myagko_rozovii_fon_krasivie_57 {
            get {
                object obj = ResourceManager.GetObject("1653390585_56-celes-club-p-myagko-rozovii-fon-krasivie-57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1653390585_56_celes_club_p_myagko_rozovii_fon_krasivie_571 {
            get {
                object obj = ResourceManager.GetObject("1653390585_56-celes-club-p-myagko-rozovii-fon-krasivie-571", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1653390585_56_celes_club_p_myagko_rozovii_fon_krasivie_572 {
            get {
                object obj = ResourceManager.GetObject("1653390585_56-celes-club-p-myagko-rozovii-fon-krasivie-572", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1663239656_b_1 {
            get {
                object obj = ResourceManager.GetObject("1663239656_b-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1663239656_b_11 {
            get {
                object obj = ResourceManager.GetObject("1663239656_b-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1663239656_b_12 {
            get {
                object obj = ResourceManager.GetObject("1663239656_b-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1670014340_10_pibig_info_p_temno_rozovie_oboi_na_telefon_instagram_10 {
            get {
                object obj = ResourceManager.GetObject("1670014340_10-pibig-info-p-temno-rozovie-oboi-na-telefon-instagram-10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1670014340_10_pibig_info_p_temno_rozovie_oboi_na_telefon_instagram_101 {
            get {
                object obj = ResourceManager.GetObject("1670014340_10-pibig-info-p-temno-rozovie-oboi-na-telefon-instagram-101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1673573485_flomaster_club_p_kot_za_kompyuterom_risunok_oboi_22 {
            get {
                object obj = ResourceManager.GetObject("1673573485_flomaster-club-p-kot-za-kompyuterom-risunok-oboi-22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1677373923_bogatyr_club_p_rozovie_oboi_na_rabochii_stol_fon_vkontakt_2 {
            get {
                object obj = ResourceManager.GetObject("1677373923_bogatyr-club-p-rozovie-oboi-na-rabochii-stol-fon-vkontakt-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _167bcae59cb8225cc85395b276bd570c {
            get {
                object obj = ResourceManager.GetObject("167bcae59cb8225cc85395b276bd570c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _389bd4f206b256ee007a3bb31c2903e4 {
            get {
                object obj = ResourceManager.GetObject("389bd4f206b256ee007a3bb31c2903e4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _389bd4f206b256ee007a3bb31c2903e41 {
            get {
                object obj = ResourceManager.GetObject("389bd4f206b256ee007a3bb31c2903e41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _389bd4f206b256ee007a3bb31c2903e42 {
            get {
                object obj = ResourceManager.GetObject("389bd4f206b256ee007a3bb31c2903e42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3939aa1aa0d33d21fd7ab47897db6e4d {
            get {
                object obj = ResourceManager.GetObject("3939aa1aa0d33d21fd7ab47897db6e4d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _473a89d931adcc373da03fd0307f70db_blues_640x618 {
            get {
                object obj = ResourceManager.GetObject("473a89d931adcc373da03fd0307f70db-blues-640x618", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _473a89d931adcc373da03fd0307f70db_blues_640x6181 {
            get {
                object obj = ResourceManager.GetObject("473a89d931adcc373da03fd0307f70db-blues-640x6181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _473a89d931adcc373da03fd0307f70db_blues_640x6182 {
            get {
                object obj = ResourceManager.GetObject("473a89d931adcc373da03fd0307f70db-blues-640x6182", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _473a89d931adcc373da03fd0307f70db_blues_640x6183 {
            get {
                object obj = ResourceManager.GetObject("473a89d931adcc373da03fd0307f70db-blues-640x6183", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _480eee5efb28df12b75213daffb24729 {
            get {
                object obj = ResourceManager.GetObject("480eee5efb28df12b75213daffb24729", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa1 {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa10 {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa2 {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa3 {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa4 {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa5 {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa6 {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa7 {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa8 {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5955872b6a0e015cf61801aa9 {
            get {
                object obj = ResourceManager.GetObject("5955872b6a0e015cf61801aa9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c3ad78aa1eee16845d9f5a7 {
            get {
                object obj = ResourceManager.GetObject("5c3ad78aa1eee16845d9f5a7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c3ad78aa1eee16845d9f5a71 {
            get {
                object obj = ResourceManager.GetObject("5c3ad78aa1eee16845d9f5a71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c3ad78aa1eee16845d9f5a72 {
            get {
                object obj = ResourceManager.GetObject("5c3ad78aa1eee16845d9f5a72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7ec82f25a23d795c7640eefe5a603986 {
            get {
                object obj = ResourceManager.GetObject("7ec82f25a23d795c7640eefe5a603986", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7ec82f25a23d795c7640eefe5a6039861 {
            get {
                object obj = ResourceManager.GetObject("7ec82f25a23d795c7640eefe5a6039861", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7ec82f25a23d795c7640eefe5a6039862 {
            get {
                object obj = ResourceManager.GetObject("7ec82f25a23d795c7640eefe5a6039862", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wp {
            get {
                object obj = ResourceManager.GetObject("wp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Розовый_фон_и_обои_красивые_картинки_и_заставки_21_фото_6 {
            get {
                object obj = ResourceManager.GetObject("Розовый-фон-и-обои-красивые-картинки-и-заставки-21-фото-6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Розовый_фон_и_обои_красивые_картинки_и_заставки_21_фото_61 {
            get {
                object obj = ResourceManager.GetObject("Розовый-фон-и-обои-красивые-картинки-и-заставки-21-фото-61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
